AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Fate - 사주 보기 웹사이트 인프라

Parameters:
  Environment:
    Type: String
    Default: dev
    Description: 환경 이름
  
  FromEmailAddress:
    Type: String
    Default: 'doyoung@minami-hd.co.jp'
    Description: 'SES에서 인증한 이메일 주소 (SES 사용 시 필수). 예: noreply@example.com'
    AllowedPattern: '^$|^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
  
  ReplyToEmailAddress:
    Type: String
    Default: ''
    Description: '답장 받을 이메일 주소 (선택사항). 비워두면 FromEmailAddress 사용'
    AllowedPattern: '^$|^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
  
  GeminiApiKey:
    Type: String
    Default: ''
    Description: 'Google Gemini API 키 (Gemini API 사용 시 필수)'
    NoEcho: true

Conditions:
  UseSES: !Not [!Equals [!Ref FromEmailAddress, '']]
  HasReplyTo: !And
    - !Not [!Equals [!Ref FromEmailAddress, '']]
    - !Not [!Equals [!Ref ReplyToEmailAddress, '']]

Resources:
  # Cognito User Pool
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub 'fate-user-pool-${Environment}'
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Schema:
        - Name: email
          Required: true
          Mutable: true
        - Name: name
          Required: false
          Mutable: true
        - AttributeDataType: String
          Name: nickname
          Required: false
          Mutable: true
      UserAttributeUpdateSettings:
        AttributesRequireVerificationBeforeUpdate:
          - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
      EmailConfiguration: !If
        - UseSES
        - EmailSendingAccount: DEVELOPER
          SourceArn: !Sub 'arn:aws:ses:${AWS::Region}:${AWS::AccountId}:identity/${FromEmailAddress}'
          From: !Ref FromEmailAddress
          ReplyToEmailAddress: !If
            - HasReplyTo
            - !Ref ReplyToEmailAddress
            - !Ref FromEmailAddress
        - !Ref 'AWS::NoValue'

  # Cognito User Pool Client
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub 'fate-client-${Environment}'
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_SRP_AUTH
      PreventUserExistenceErrors: ENABLED

  # Cognito Identity Pool (선택사항 - 필요시 사용)
  IdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: !Sub 'fate-identity-pool-${Environment}'
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        - ClientId: !Ref UserPoolClient
          ProviderName: !GetAtt UserPool.ProviderName

  # S3 버킷 (프로필 이미지 저장용)
  ProfileImageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'fate-profile-images-${Environment}-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - HEAD
            AllowedOrigins:
              - '*'
            MaxAge: 3000
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldVersions
            Status: Enabled
            NoncurrentVersionExpirationInDays: 30

  # S3 버킷 정책 (나중에 Cognito Identity Pool을 통한 접근 설정)
  # 현재는 Lambda를 통해 업로드하도록 구현 예정
  # ProfileImageBucketPolicy:
  #   Type: AWS::S3::BucketPolicy
  #   Properties:
  #     Bucket: !Ref ProfileImageBucket
  #     PolicyDocument:
  #       Statement:
  #         - Sid: AllowCognitoUsers
  #           Effect: Allow
  #           Principal:
  #             Federated: cognito-identity.amazonaws.com
  #           Action:
  #             - s3:GetObject
  #             - s3:PutObject
  #             - s3:DeleteObject
  #           Resource: !Sub '${ProfileImageBucket}/*'
  #           Condition:
  #             StringEquals:
  #               'cognito-identity.amazonaws.com:aud': !Ref IdentityPool
  #             'ForAnyValue:StringLike':
  #               'cognito-identity.amazonaws.com:amr': authenticated

  # DynamoDB 테이블
  FateTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub 'fate-${Environment}'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

  # API Gateway
  FateApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub 'fate-api-${Environment}'
      StageName: !Sub '${Environment}'
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"

  # Lambda 함수: 사주 계산
  FateCalculatorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'fate-calculator-${Environment}'
      CodeUri: ../lambda/fate-calculator
      Handler: index.handler
      Runtime: nodejs18.x
      Environment:
        Variables:
          FATE_TABLE_NAME: !Ref FateTable
          GEMINI_API_KEY: !Ref GeminiApiKey
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FateTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref FateApi
            Path: /fate
            Method: post

  # Lambda 함수: 비밀번호 변경
  ChangePasswordFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'change-password-${Environment}'
      CodeUri: ../lambda/change-password
      Handler: index.handler
      Runtime: nodejs18.x
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - cognito-idp:ChangePassword
                - cognito-idp:GetUser
              Resource: !GetAtt UserPool.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref FateApi
            Path: /change-password
            Method: post

  # Lambda 함수: 프로필 이미지 업로드 URL 생성
  UploadProfileImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'upload-profile-image-${Environment}'
      CodeUri: ../lambda/upload-profile-image
      Handler: index.handler
      Runtime: nodejs18.x
      Environment:
        Variables:
          PROFILE_IMAGE_BUCKET: !Ref ProfileImageBucket
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref ProfileImageBucket
        - Statement:
            - Effect: Allow
              Action:
                - cognito-idp:GetUser
              Resource: !GetAtt UserPool.Arn
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref FateApi
            Path: /upload-profile-image/{extension}
            Method: get

  # Lambda 함수: 사주 기록 조회
  GetFateHistoryFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub 'get-fate-history-${Environment}'
      CodeUri: ../lambda/get-fate-history
      Handler: index.handler
      Runtime: nodejs18.x
      Environment:
        Variables:
          FATE_TABLE_NAME: !Ref FateTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref FateTable
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref FateApi
            Path: /fate/{id}
            Method: get
        ApiEventList:
          Type: Api
          Properties:
            RestApiId: !Ref FateApi
            Path: /fate
            Method: get

  # S3 버킷 (프론트엔드 호스팅용)
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'fate-frontend-${Environment}-${AWS::AccountId}'
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
              - HEAD
            AllowedOrigins:
              - '*'
            MaxAge: 3000
      VersioningConfiguration:
        Status: Enabled

  # CloudFront Origin Access Identity (OAI) - OAC 대신 사용
  FrontendOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub 'OAI for ${FrontendBucket}'

  # CloudFront Distribution
  FrontendDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        HttpVersion: http2and3
        DefaultRootObject: index.html
        PriceClass: PriceClass_100
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${FrontendOriginAccessIdentity}'
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6 # Managed-CachingOptimized
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 300

  # S3 버킷 정책 (CloudFront OAI를 통한 접근만 허용)
  # 참고: CloudFormation의 순환 참조 문제를 피하기 위해 
  # 배포 후 수동으로 버킷 정책을 설정하거나, 별도 스크립트로 설정해야 할 수 있습니다.
  # 또는 CloudFront가 S3 버킷에 직접 접근할 수 있도록 버킷 정책을 설정합니다.
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DependsOn: FrontendOriginAccessIdentity
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Sid: AllowCloudFrontAccess
            Effect: Allow
            Principal:
              AWS: !Sub 
                - 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${OAIId}'
                - OAIId: !Ref FrontendOriginAccessIdentity
            Action: s3:GetObject
            Resource: !Sub 'arn:aws:s3:::${FrontendBucket}/*'

Outputs:
  ProfileImageBucket:
    Description: S3 버킷 이름 (프로필 이미지 저장용)
    Value: !Ref ProfileImageBucket
    Export:
      Name: !Sub '${AWS::StackName}-ProfileImageBucket'

  ApiUrl:
    Description: API Gateway 엔드포인트 URL
    Value: !Sub 'https://${FateApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}'
  
  TableName:
    Description: DynamoDB 테이블 이름
    Value: !Ref FateTable

  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolId'

  UserPoolClientId:
    Description: Cognito User Pool Client ID
    Value: !Ref UserPoolClient
    Export:
      Name: !Sub '${AWS::StackName}-UserPoolClientId'

  FrontendBucket:
    Description: S3 버킷 이름 (프론트엔드 호스팅용)
    Value: !Ref FrontendBucket
    Export:
      Name: !Sub '${AWS::StackName}-FrontendBucket'

  FrontendDistributionId:
    Description: CloudFront Distribution ID
    Value: !Ref FrontendDistribution
    Export:
      Name: !Sub '${AWS::StackName}-FrontendDistributionId'

  FrontendUrl:
    Description: 프론트엔드 접근 URL (CloudFront)
    Value: !Sub 'https://${FrontendDistribution.DomainName}'
    Export:
      Name: !Sub '${AWS::StackName}-FrontendUrl'
